/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanager.controller.view.component;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import projectmanager.controller.view.component.exception.ValidationException;
import projectmanager.controller.view.component.validator.Validator;

/**
 *
 * @author EMA
 */
public class InputTextAreaPanel extends javax.swing.JPanel implements GetValue {
    private Validator validator;
    /**
     * Creates new form InputTextAreaPanel
     */
    public InputTextAreaPanel() {
        initComponents();
        txtAreaValue.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaValue = new javax.swing.JTextArea();
        lblErrorValue = new javax.swing.JLabel();

        lblText.setText("Text:");

        txtAreaValue.setColumns(10);
        txtAreaValue.setRows(5);
        jScrollPane1.setViewportView(txtAreaValue);

        lblErrorValue.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorValue.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorValue)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorValue))
        );
    }// </editor-fold>//GEN-END:initComponents
  public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public JTextArea getTxtAreaValue() {
        return txtAreaValue;
    }
    
    public void setValidator(Validator validator) {
        this.validator = validator;
    }
    
    @Override
    public Object getValue() throws Exception {
        lblErrorValue.setText("");
        try {
            if (validator != null) validator.validate(txtAreaValue.getText().trim());
            return txtAreaValue.getText();
        } catch(ValidationException ve){
            lblErrorValue.setText(ve.getMessage());
            throw new Exception(ve.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    private javax.swing.JTextArea txtAreaValue;
    // End of variables declaration//GEN-END:variables
}
