/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanager.controller.view.component;

import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import projectmanager.controller.view.component.exception.ValidationException;
import projectmanager.controller.view.component.validator.Validator;

/**
 *
 * @author EMA
 */
public class InputPasswordPanel extends javax.swing.JPanel implements GetValue{
    private Validator validator;
    /**
     * Creates new form InputPasswordPanel
     */
    public InputPasswordPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        txtPasswordValue = new javax.swing.JPasswordField();
        lblErrorValue = new javax.swing.JLabel();

        lblText.setText("jLabel1");

        txtPasswordValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordValueActionPerformed(evt);
            }
        });

        lblErrorValue.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorValue.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorValue, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtPasswordValue)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText)
                    .addComponent(txtPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorValue))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    private javax.swing.JPasswordField txtPasswordValue;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public JTextField getTxtPasswordValue() {
        return txtPasswordValue;
    }
    
    public void setValidator(Validator validator) {
        this.validator = validator;
    }
    @Override
    public Object getValue() throws Exception {
        lblErrorValue.setText("");
        try {
            if (validator != null) validator.validate(txtPasswordValue);
            return txtPasswordValue.getPassword();
        } catch(ValidationException ve){
            lblErrorValue.setText(ve.getMessage());
            throw new Exception(ve.getMessage());
        }
    }
}
